[package]
authors = ["Ockam Developers"]
edition = "2018"
name = "ockam-vault"
version = "0.1.0"

[dependencies]
ockam-common = { version = "0.1", path = "../../common" }
arrayref = "0.3"
zeroize = { version = "1.1", features = ["zeroize_derive"] }
downcast = "0.10.0"
cfg-if = "1.0"
