[package]
authors = ["Ockam Developers"]
edition = "2018"
name = "ockam-vault-ffi"
version = "0.1.0"

[lib]
crate-type = ["staticlib", "rlib", "cdylib"]

[profile.release]
lto = true

[dependencies]
ockam-common = { version = "0.1", path = "../../common", features = ["ffi"] }
ockam-vault-software = { version = "0.1", path = "../software" }
ockam-vault-file = { version = "0.1", path = "../file" }
ffi-support = { version = "0.4"}
lazy_static = { version = "1.4"}
