[package]
authors = ["Ockam Developers"]
edition = "2018"
name = "ockam-kex-ffi"
version = "0.1.0"

[lib]
crate-type = ["staticlib", "rlib", "cdylib"]

[profile.release]
lto = true

[dependencies]
ockam-common = { version = "0.1", path = "../../common" }
ockam-kex-xx = { version = "0.1", path = "../xx" }
ockam-vault = { version = "0.1", path = "../../vault/traits" }
ockam-vault-software = { version = "0.1", path = "../../vault/software" }
ffi-support = { version = "0.4.0" }
