[package]
name = "ockam-common"
version = "0.1.0"
authors = ["Ockam Developers"]
edition = "2018"

[features]
default = []
ffi = ["ffi-support"]

[dependencies]
cfg-if = "1.0"
ffi-support = { version = "0.4.0", optional = true }